### PR TITLE
Add retrospective 1 and sprint plan 2

### PR DESCRIPTION
**Pull request by bvanwijk**
Add retrospective 1 and sprint plan 2

### CODE REVIEW

**Comment by egedebruin** [comment]
Looks good, i agree that this is mergeable

**Comment by Kingdorian** [comment]
Seems fine.

**Comment by NaomidR** [comment]
Yes, this is ready to hand it in. The only thing is that maybe 'smaller tasks' in the adjustments could be explained as tasks exceeding 5 hours.

**Comment by jochem725** [comment]
Looks good, I agree with merging.

**Pull request merged**
