### PR TITLE
Fix maven-site malfunctioning

### PR DESCRIPTION
**Pull request by jochem725**
Maven site was broken in my setup.
It appears this was related to checkstyle.xml.

Is anyone affected by the same problem and does this pr solve the problem?

### CODE REVIEW

**Comment by bvanwijk** [comment]
It works for me, is it right that the reportings of maven site for pmd, checkstyle and findbugs are in backend/target/site instead of target/site?

**Comment by jochem725** [comment]
@bvanwijk Yes, this is correct for the current setup, since the master pom file is still in place, running maven site on each individual project. Maybe we should decide to get rid of the master pom file in the future.

**Comment by Kingdorian** [comment]
Well we xd decided to keep te master pom file just in case.  But I think we won't need it anytime soon.

**Comment by jochem725** [comment]
@Kingdorian I've added #40 so we can discuss about this later.

**Comment by bvanwijk** [comment]
Alright I think we can merge it then

**Pull request merged**
