### PR TITLE
Cleanup warnings

### PR DESCRIPTION
**Pull request by bvanwijk**
I fixed some small checkstyle and findbugs warnings.

### CODE REVIEW

**Comment by jochem725** [comment]
Seems fine, thanks for fixing this @bvanwijk. Maybe we should mention somewhere why the FindBugs warning was excluded.

**Comment by bvanwijk** [comment]
@jochem725 it is mentioned in the findbugs-exclude.xml file and above the method where the warning occurs.

**Comment by jochem725** [comment]
@bvanwijk Oh I missed that, then I think we can merge this.

**Comment by NaomidR** [comment]
Looks fine, this can be merged.

**Pull request merged**
