### PR TITLE
Web interface

### PR DESCRIPTION
**Pull request by jochem725**
This is a basic version of the web interface. For a future sprint, we can easily use these elements to automatically generate the page.

### CODE REVIEW

**Comment by Kingdorian** [comment]
Looks good for a basic version. I agree with merging.

**Comment by NaomidR** [comment]
Yes this can be merged into develop! Next sprint we can build on this.

**Comment by bvanwijk** [comment]
Looks as a good basis you can merge it.

**Comment by jochem725** [comment]
Great, I'll start merging.

**Pull request merged**
