### PR TITLE
NodeJS Configuration file + Refactor

### PR DESCRIPTION
**Pull request by jochem725**
I've added a config.json file, which is generated automatically on first start.

It's persistent over multiple requires, so you can just call require and use it in all modules.
I've also added this pattern to the logger, to make it as easy as possible to use these modules.

### CODE REVIEW

**Comment by bvanwijk** [comment]
Looks good, I agree with merging.

**Comment by NaomidR** [comment]
Nice that you made it persistent. I think that this can be merged.

**Comment by egedebruin** [comment]
Good work, and also nice to implement it with the logger.

**Comment by Kingdorian** [comment]
Looks good!

**Comment by jochem725** [comment]
I'll merge it then!

**Pull request merged**
