### PR TITLE
Direct add tag

### PR DESCRIPTION
**Pull request by egedebruin**
This ensures that the tags are directly added, deleted and updated, instead of only when clicking on save&close.
This also ensures that the tags are correctly updated in the presets, when deleting and updating tags.

### CODE REVIEW

**Comment by Kingdorian** [comment]
Looks good, I think we can merge this.

**Comment by jochem725** [comment]
Looks fine, I agree with merging.

**Comment by bvanwijk** [comment]
When I add a preset with a tag, then I change this tag the tag in the preset is updated correctly but when I reload the update tags window the old tag and the new tag are both visible.
Maybe you could take a look at this?

**Comment by egedebruin** [comment]
@bvanwijk, I think with the latest commit that should be fixed.

**Comment by bvanwijk** [comment]
I changed a small thing, I think you can merge it now.

**Comment by NaomidR** [comment]
Looks good, I agree with merging this.

**Pull request merged**
