### PR TITLE
Fix failing test (because of charset) and ipcamera hotfix

### PR DESCRIPTION
**Pull request by Kingdorian**
Hotfix for the failing test of the max logsize (because of charset) on Bryan's (and possibly others) machine(s).

@bvanwijk

### CODE REVIEW

**Comment by bvanwijk** [comment]
It still fails on my machine.
The LogWriterTest.testMaxLogSize test gives a NoSuchFile error for the file logs\maxlogsizetestlog-old.log

**Comment by Kingdorian** [comment]
@bvanwijk I'll look into this for me it creates the file if it does not yet exist, can you please make sure you have the right acces rights setup in the logs dir? Also does it pass if you manually create an empty file called: logs\maxlogsizetestlog-old.log?

**Comment by jochem725** [comment]
It appears to be working correctly for me. Besides that, maybe you could add a tearDown for the test log files created, so they don't 'pollute' the log folder.

**Comment by Kingdorian** [comment]
@jochem725 thats a good idea, I'll add that (late) tonight or tomorrow.

**Comment by bvanwijk** [comment]
@Kingdorian when I create the file manually it still fails. After I have run maven the file I created manually is deleted.

**Comment by bvanwijk** [comment]
@Kingdorian I think I fixed the problem. The rename operation in the hardWrite method dit not succeed, because the system saw it was still in use by another process.

**Comment by jochem725** [comment]
The fix suggested by @bvanwijk is not affecting my machine.

**Comment by Kingdorian** [comment]
@bvanwijk Silly windows.. it works on my machine so I think we can merge this if you agree.

**Comment by bvanwijk** [comment]
Yes, I agree with merging.

**Pull request merged**
