### PR TITLE
Fix checkstyle and findbugs

### PR DESCRIPTION
**Pull request by NaomidR**
The few checkstyle and PMD warnings in develop are now  gone.

### CODE REVIEW

**Comment by Kingdorian** [comment]
I think these changes are a bit to small for a complete pullrequest since its just a  tiny refactor this can be done when making changes to a class when working on a feature. We can merge this but in the future I  think we should avoid this kind of "fix checkstyle" or "small refactor" pullrequests and just icorporate the changes in larger pull requests. This avoids clutter of unused pull requests like this one.

**Comment by NaomidR** [comment]
You commented this in the other pull request as well and I can understand why you're saying this. However, I discussed this with @jochem725 this morning and we decided to just make a pull request so that these errors are fixed. There's no need to go over this in very much depth though.

**Comment by Kingdorian** [comment]
For the other pull request I made this comment for I now understand why that should be a pullrequest.

Just discussed this with @jochem725  too and he indeed told me you discussed this but he agreed with me on this being to small of a change for a pullrequest.

**Comment by bvanwijk** [comment]
I agree with merging.

**Pull request merged**
