### PR TITLE
Fix preset database

### LINKED ISSUE #169: Preset and simplepreset id
It is now possibile to have a preset and a simplepreset with the same id in the database, this should not be possible for connecting with the tags.

### PR DESCRIPTION
**Pull request by egedebruin**
This will fix #169 
There is now a preset table which connects with the tags and presetlist. The IPpreset and simplepreset tables connect to the camera.

### CODE REVIEW

**Comment by bvanwijk** [comment]
Is it correct tags added to a preset are not in the tagpreset table in the database in this branch?

**Comment by egedebruin** [comment]
That shouldn't be correct and I think I know why. I will try to fix it.

**Comment by egedebruin** [comment]
I have fixed it, the tags are now correctly updated. Please check if it still works.

**Comment by bvanwijk** [comment]
I saw the edit preset call was not called from the UI. I have fixed that, now everything is working correctly. If somelse confirms, I think you can merge this.

**Comment by jochem725** [comment]
It seems to be working for me now, I agree with merging.

**Pull request merged**
