### PR TITLE
Delete tag endpoint

### PR DESCRIPTION
**Pull request by Kingdorian**
Implemented deleting tags via the removetag endpoint.

### CODE REVIEW

**Comment by jochem725** [comment]
Looks good, however I think you forgot to add the `removetag` endpoint to the `PresetsHandler`

**Comment by Kingdorian** [comment]
Thanks, I totally forgot that.

**Comment by Kingdorian** [comment]
@jochem725 this should be fixed now.

**Comment by bvanwijk** [comment]
I think we can merge this now.

**Pull request merged**
