### PR TITLE
Tag Window CSS

### PR DESCRIPTION
**Pull request by jochem725**
I've upgraded the tag window styling to match the edit performance window.
Please verify if tags are still added correctly. Editing a tag name is not functioning, maybe @egedebruin can take a look at this.

### CODE REVIEW

**Comment by egedebruin** [comment]
The tags are now updated correctly.
It looks good and I think this can be merged.

**Comment by jochem725** [comment]
It works fine now, thanks Ege.

**Comment by bvanwijk** [comment]
There is a style error with the lettertype in the tags window

**Comment by jochem725** [comment]
I've resolved the issues, please confirm the text is formatted correctly now.

**Comment by bvanwijk** [comment]
There is a bug when you click edit name in the performance window twice.

**Comment by jochem725** [comment]
I've fixed the issue you were pointing out @bvanwijk, now everything should function correctly.

**Pull request merged**
