### PR TITLE
Other name to newly added tag

### PR DESCRIPTION
**Pull request by egedebruin**
When creating a new tag, the default first was "new", but it is changed to "tag" + index of new tag. I think this is better then first, but maybe someone has a better idea.

### CODE REVIEW

**Comment by Kingdorian** [comment]
I think we can merge this.

**Comment by bvanwijk** [comment]
Looks good, maybe you could add a space between tag and the index.

**Comment by bvanwijk** [comment]
I agree with merging now.

**Comment by NaomidR** [comment]
I don't have anything to add. I think we can merge this!

**Pull request merged**
