### PR TITLE
Spamming of the database is now to a log file

### PR DESCRIPTION
**Pull request by egedebruin**
The database will not dump text to the console anymore, but to a different log file.

#84

### CODE REVIEW

**Comment by jochem725** [comment]
Looks fine @egedebruin, however I think this is not going to work on all operating systems due to the line separator. I think `File.separator` instead of `/` is the solution for this.

**Comment by bvanwijk** [comment]
I agree with Jochem

**Comment by Kingdorian** [comment]
Also a better name for the log would be database.log, or even database-[database_name].log.

**Comment by NaomidR** [comment]
I agree with Jochem and Dorian. The rest looks good.

**Comment by egedebruin** [comment]
I have fixed the things you commented on and made it able to use the database if the database is already present before the program start ups, fixing #89

**Comment by bvanwijk** [comment]
I'm happy you fixed this, it works for me.
However there are some checkstyle and findbugs warnings introduced, I would like it if you can fix them.

**Comment by bvanwijk** [comment]
Looks good, I agree with merging.

**Pull request merged**
