### PR TITLE
Disable auto presetcreation when no camera is selected

### LINKED ISSUE #207: Modal autopresetcreation available when no camera is selected.

### PR DESCRIPTION
**Pull request by bvanwijk**
Fix #207

### CODE REVIEW

**Comment by egedebruin** [comment]
Looks fine, good small fix.

**Comment by Kingdorian** [comment]
Looks good, maybe we also want to disable this button if the camera is in use by someone else.

**Comment by bvanwijk** [comment]
@Kingdorian Yes, that would be nice, but the problem with this is the backend doesn't supply information about which client has the camera in use. So you don't no if you're the client with the camera in use or another client has the camera in use.

**Comment by Kingdorian** [comment]
We could possibly add that but I'll create an issue for that since its outside the scope of this branch/sprint item.

**Comment by jochem725** [comment]
I agree with Dorian, I think you can merge this now 😄

**Pull request merged**
