### PR TITLE
Sprint plan 8, retrospective sprint 7 and updated architecture design

### PR DESCRIPTION
**Pull request by bvanwijk**
Sprint plan 8, retrospective sprint 7 and updated architecture design

### CODE REVIEW

**Comment by NaomidR** [comment]
Looks good, I agree with merging this.

**Comment by jochem725** [comment]
I've made some small changes, I think this can be merged now.

**Comment by egedebruin** [comment]
I think this can be merged.

**Comment by Kingdorian** [comment]
I think we can merge this.

**Pull request merged**
