### PR TITLE
UI Colors

### PR DESCRIPTION
**Pull request by jochem725**
I've replaced all non-functional button colors with a less distracting color.
Only buttons which need a functional color (toggles, deletion buttons etc.) still have their original color.

### CODE REVIEW

**Comment by bvanwijk** [comment]
Looks much better, I agree with merging.

**Comment by Kingdorian** [comment]
Looks much less messy. But the buttons for the modals might still be a bit to colorfull.
image
image

**Comment by jochem725** [comment]
@Kingdorian I agree with you, maybe making the close buttons gray instead of green would be better. What do you propose?

**Comment by NaomidR** [comment]
I agree with @Kingdorian about the buttons in the modals, they don't really have a functionality. Gray would be better indeed. After you changed this, I agree with merging it.

**Comment by Kingdorian** [comment]
@jochem725 Yes (blue\ish) gray would be better.

**Comment by jochem725** [comment]
I've now made all green buttons gray.

**Comment by egedebruin** [comment]
Is it correct that the edit preset button should be red?

**Comment by jochem725** [comment]
@egedebruin Yes, in this branch the color is functional (editing, not editing). In #230 this color is removed and replaced with a toggle button.

**Comment by egedebruin** [comment]
Ok, then I agree with merging.

**Pull request merged**
