### PR TITLE
Small unit interfaces

### PR DESCRIPTION
**Pull request by bvanwijk**
I have reduced the amount of parameters of some methods as suggested by the bettercodehub tool from SIG.

### CODE REVIEW

**Comment by Kingdorian** [comment]
I think the number of parameters in the IPCamera preset still might be a bit to high.

**Comment by bvanwijk** [comment]
@Kingdorian yes, it's still a bit high. What do you think is the best solution for this? Adding the autofocus, autoiris, focus, iris to the position class? or create a seperate class IPCameraPosition with these values?

**Comment by Kingdorian** [comment]
Maybe combine the autoIris boolean and value into a single object the same can be done for the autofocus. This reduces it already with 2. I think the id can be removed completely since this is reassigned after creation of the preset by the preset controller anyway but I might be wrong.

**Comment by bvanwijk** [comment]
The preset id is not in the constructor of a preset, it's the cameraID which is in the constructor.
Sounds like a good idea for the iris and focus, I will implemented that.

**Comment by jochem725** [comment]
I agree with Dorian about the iris and focus parameters. After this is fixed, I agree with merging.

**Comment by Kingdorian** [comment]
This indeed fixes the bettercodehub warning. 
image

**Comment by jochem725** [comment]
Let's merge it then.

**Pull request merged**
