### PR TITLE
settings view

### PR DESCRIPTION
**Pull request by bvanwijk**
Start settings with 1 and increate size of sliders

### CODE REVIEW

**Comment by Kingdorian** [comment]
Looks great I think this can be merged.

**Comment by NaomidR** [comment]
Looks good indeed, I agree with merging.

**Comment by jochem725** [comment]
It seems to be bugging for me on 2 digit number values.
schermafbeelding 2016-06-14 om 11 22 21

**Comment by egedebruin** [comment]
It works fine for me, I don't have the same problem as Jochem.

**Comment by bvanwijk** [comment]
@jochem725 I think I've fixed the problem could you verify this?

**Comment by jochem725** [comment]
@bvanwijk It is indeed fixed, I think this can be merged now.

**Pull request merged**
