### PR TITLE
Fix drawing subviews aspectratio

### PR DESCRIPTION
**Pull request by Kingdorian**
I fixed the subviews aspectratio.

### CODE REVIEW

**Comment by jochem725** [comment]
Seems fine, I think this can be merged.

**Comment by jochem725** [comment]
I've discovered some checkstyle issues, I think these should be fixed prior to merging.

**Comment by bvanwijk** [comment]
After the checkstyle warnings are fixed, I think this can be merged

**Comment by NaomidR** [comment]
I've fixed the checkstyle warnings, I think this can be merged.

**Pull request merged**
