### PR TITLE
Add semaphore for flushing

### PR DESCRIPTION
**Pull request by Kingdorian**
Fixes https://github.com/Kingdorian/Contextproject-BeNine/issues/206 I cannot replicate the behaviour described in the issue with this fix, can someone confirm this?

### CODE REVIEW

**Comment by bvanwijk** [comment]
I've tested it, and I didn't get the issue. I agree with merging.

**Comment by jochem725** [comment]
After running it for over 25 minutes, it appears a nullpointerexception is still possible. 
schermafbeelding 2016-06-15 om 12 26 29

**Comment by jochem725** [comment]
In a second run, the same exception appeared somewhere near 100 minutes.

**Comment by Kingdorian** [comment]
@jochem725 @bvanwijk  I changed this a bit so it should now not happen anymore. I tested it for 2 hours on my laptop with 3 clients and did not get an exception.

**Comment by jochem725** [comment]
Excellent, let's merge it.

**Pull request merged**
