### PR TITLE
Deployable

### PR DESCRIPTION
**Pull request by bvanwijk**
There is now a zip file generated containing the executable for the backend server and the frontend server.

### CODE REVIEW

**Comment by Kingdorian** [comment]
Maybe it would be good to add to the readme how to create a deployable. I think we should also include a startserver .sh file for unix systems instead of the .cmd.

**Comment by bvanwijk** [comment]
@Kingdorian I agree, but I think it would be better to ask somebody with a unix system to create this.

**Comment by Kingdorian** [comment]
Hahah that's true, I'll add it tomorrow.

**Comment by Kingdorian** [comment]
@bvanwijk Should work now, can someone with an unix system @jochem725  confirm the bash script works? Also is the .cmd script verified to work by someone with a windows system like @NaomidR or @egedebruin ?

**Comment by jochem725** [comment]
I've resolved an issue with the decimal format locale. Please verify if it is now working on all system languages. @Kingdorian I think the .sh file needs changed permissions (`chmod -x` if I'm correct) before it becomes executable.

**Comment by egedebruin** [comment]
The .cmd script works for me.

**Comment by Kingdorian** [comment]
@jochem725 I'm aware that the .sh file needs execute permissions, this can ofcourse not be done automatically but I'll add it to the readme.

**Comment by jochem725** [comment]
@Kingdorian I believe it is actually possible using the `fileMode` configuration, described [here](http://maven.apache.org/plugins/maven-assembly-plugin/assembly.html#sources).
I think adding `<fileMode>0755</fileMode>` below `</includes>` should fix it.

**Comment by jochem725** [comment]
@Kingdorian I've implemented this, and now the .sh file is automatically given execute permissions. I think this can be merged now.

**Comment by bvanwijk** [comment]
I think everything works correctly now, the next person can merge it.

**Pull request merged**
