### PR TITLE
Endpoint auto preset

### PR DESCRIPTION
**Pull request by Kingdorian**

### CODE REVIEW

**Comment by jochem725** [comment]
Seems fine, maybe you can also add a button in the user interface so we can call the pyramid creator.

**Comment by bvanwijk** [comment]
Seems fine, I think this can be merged.

**Comment by Kingdorian** [comment]
@jochem725 will do.

**Comment by jochem725** [comment]
Seems like a great idea.

**Comment by egedebruin** [comment]
Looks good, I agree with merging.

**Pull request merged**
