### PR TITLE
Develop ui fix

### PR DESCRIPTION
**Pull request by jochem725**
This should resolve the UI issues on develop.

### CODE REVIEW

**Comment by jochem725** [comment]
I've fixed the slider orientation on responsive layouts, it should at least look little bit better now. Please check if it looks correct.

**Comment by bvanwijk** [comment]
I think it can be merged now, I fixed a small problem with disappearing buttons when not supported.

**Comment by jochem725** [comment]
Great find @bvanwijk, I think we can merge it now.

**Comment by egedebruin** [comment]
It also looks good for me.

**Pull request merged**
