### PR TITLE
Camera inuse

### PR DESCRIPTION
**Pull request by bvanwijk**
It is now possible to see in the UI which camera's are in use by other users.

### CODE REVIEW

**Comment by jochem725** [comment]
Great to see this working, I agree with merging.

**Comment by Kingdorian** [comment]
Looks good, I would move the timeout setting to the config file however. Also 5000ms might be a bit short since the auto preset creation sometimes spends more time waiting then this.

**Comment by bvanwijk** [comment]
@Kingdorian I don't completely understand what the auto preset creation has to do with this. The clients say to the backend every few seconds which camera they have in use. During the auto preset creation the client will keep doing this so the others know which camera is in use. This does not block other clients to use the camera. 
Do you have a suggestion how to reach the config from the basicCamera class since a static call to the serverController seems not like a good idea to me?

**Comment by Kingdorian** [comment]
Well that way if the camera is auto creating and for some reason it drops the camera will be released but the auto preset creation process is still going on since the client does not actively interact with this. It does however interact with the camera's to say they're busy every once in a while (for now it is 6 seconds but this could be shortened). 

It might not be the most elegant method but you could create a new config object in the basicCamera class. But on second thought it does not add a lot of value to have this in the config maybe. If it will not be retrieved from the config I would suggest changing the name of _useTimeOut_ to upper case to indicate its a constant.

**Comment by bvanwijk** [comment]
@Kingdorian I have changed useTimeOut to upper case.

**Comment by Kingdorian** [comment]
@bvanwijk  great but the autopreset creation issue when clients disconnect is still not solved I don't think we should merge this before it is.

**Comment by bvanwijk** [comment]
@Kingdorian What do you propse as a solution how many seconds must the timeout be?

**Comment by bvanwijk** [comment]
@Kingdorian I think I have fixed it now, before auto creating every preset the camera is set in use for 7 seconds. The auto creating of 1 preset takes around 6 seconds after which the camera is set in use again. So the camera stays in use during the auto preset creation even if the client crashes.

**Comment by Kingdorian** [comment]
I think we can merge this now.

**Comment by jochem725** [comment]
If someone else agrees, this can be merged.

**Comment by NaomidR** [comment]
I agree with merging this

**Pull request merged**
